name: South Fitted Wardrobe CI/CD
on:
  push:
    branches:
      - main
      - dockerization

# Global variables
env:
  USER_NAME: ${{ github.actor }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USER_NAME: ${{ secrets.SERVER_USER_NAME }}
  REPOSITORY: ${{ github.REPOSITORY_OWNER }}

# Jobs
jobs:

# Continuous integration
  # CI:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #     contents: read

  #   steps:
  #   # Clone the repo
  #     - name: Check Out Repo 
  #       uses: actions/checkout@v2

  #   # Build the image 
  #     - name: Build Image
  #       run: |
  #         VERSION=$(echo "${GITHUB_SHA:0:6}")
  #         echo $VERSION
  #         REPO_LOWER=$(echo $REPOSITORY | tr '[A-Z]' '[a-z]')
  #         IMAGE_NAME=ghcr.io/fazi1live/south_fitted_wardrobe:latest
  #         docker build -t $IMAGE_NAME . && docker images

  #   # Login to GitHub's container registry
  #     - name: Registry Login
  #       run: echo $GITHUB_TOKEN | docker login -u $USER_NAME --password-stdin ghcr.io

  #   # Push the image to the registry
  #     - name: Push Image
  #       run: docker push ghcr.io/fazi1live/south_fitted_wardrobe:latest

  CD:
    needs: CI
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    # Clone the repo
      - name: Check Out Repo 
        uses: actions/checkout@v2

    # Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SERVER_SSH_KEY" > ~/.ssh/id_ecdsa
          chmod 600 ~/.ssh/id_ecdsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ecdsa
          ssh-keyscan -H $SERVER_IP > ~/.ssh/known_hosts

    # Deployment
      - name: Deployment
        run: |
          echo "docker pull ghcr.io/fazi1live/south_fitted_wardrobe:latest" | ssh $SERVER_USER_NAME@$SERVER_IP
          echo "docker stop main" | ssh $SERVER_USER_NAME@$SERVER_IP
          echo "docker run -p 3000:3000 --name main -d ghcr.io/fazi1live/south_fitted_wardrobe:latest"