name: South Fitted Wardrobe CI/CD
on:
  push:
    branches:
      - main
      - dockerization

# Global variables
env:
  USER_NAME: ${{ github.actor }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USER_NAME: ${{ secrets.SERVER_USER_NAME }}
  REPOSITORY: ${{ github.REPOSITORY_OWNER }}

# Jobs
jobs:

# Continuous integration
  CI:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    # Clone the repo
      - name: Check Out Repo 
        uses: actions/checkout@v2

    # Build the image 
      - name: Build Image
        run: |
          VERSION=$(echo "${GITHUB_SHA:0:6}")
          echo $VERSION
          REPO_LOWER=$(echo $REPOSITORY | tr '[A-Z]' '[a-z]')
          IMAGE_NAME=ghcr.io/$USER_NAME/south_fitted_wardrobe:latest
          docker build -t $IMAGE_NAME . && docker images

    # Login to GitHub's container registry
      - name: Registry Login
        run: echo $GITHUB_TOKEN | docker login -u $USER_NAME --password-stdin ghcr.io

    # Push the image to the registry
      - name: Push Image
        run: docker push ghcr.io/$USER_NAME/south_fitted_wardrobe:latest